ALTER TABLE "QuoteRule" ADD COLUMN IF NOT EXISTS "modalBgColor" TEXT;
ALTER TABLE "QuoteRule" ADD COLUMN IF NOT EXISTS "modalTextColor" TEXT;
ALTER TABLE "QuoteRule" ADD COLUMN IF NOT EXISTS "inputBgColor" TEXT;
ALTER TABLE "QuoteRule" ADD COLUMN IF NOT EXISTS "inputTextColor" TEXT;
