client_id = "1a185a141435cf91bd47d2b0c009c945"
name = "QuoteSnap"
application_url = "https://quote-snap-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request"]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/redact"]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = ["shop/redact"]
  uri = "/webhooks/shop/redact"

[access_scopes]
scopes = "read_products,read_customers,write_customers"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://quote-snap-production.up.railway.app/auth/callback",
  "https://quote-snap-production.up.railway.app/billing-return"
]

[app_proxy]
url = "https://quote-snap-production.up.railway.app/apps/quotesnap"
subpath = "quotesnap"
prefix = "apps"

[[extensions]]
type = "theme"
name = "storefront-quote"
handle = "storefront-quote"
